name: rdp-windows

on:
  push:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download
        run: Invoke-WebRequest https://piping-vnc-server-for-windows.nwtgck.org/#?server=https%3A%2F%2Fppng.io&cs_path=fkunn1326&sc_path=fkunn1326 -OutFile utils.zip
      - name: Extract
        run: Expand-Archive utils.zip
      - name: Start
        run: .\utils\start.bat
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
