name: rdp-windows

on:
  push:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download
        run: Invoke-WebRequest https://github.com/fkunn1326/github-ci/raw/main/utils.zip -OutFile utils.zip
      - name: Extract
        run: Expand-Archive utils.zip
      - name: Start VNC
        run: start ./utils/tools/UltraVnc_1342/x64/winvnc.exe
