name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    container:
      image: codercom/code-server:latest
    steps:
      - name: Run code-server
        run: |
          sudo curl -OL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          sudo echo -e ${{secrets.CF_CERT}} > ~/.cloudflared/cert.pem
          cloudflared tunnel create coder
          sudo code-server
