name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    container:
      image: codercom/code-server:latest
    steps:
      - name: Run code-server
        run: |
          sudo wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb
          sudo code-server --link
