name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    steps:
      - name: Run code-server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
          curl -OL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          touch ./cert.pem
          
          cat <<EOL >> ./cert.pem
          ${{secrets.CF_CERT}}
          EOL
          
          cat <<EOL >> ./config.yml
          ${{secrets.CF_YAML}}
          EOL

          cat <<EOL >> ./af573896-2e34-45cd-9037-1bbb9138bd27.json
          ${{secrets.CF_CFG}}
          EOL
          
          code-server --port=8080 &
          cloudflared tunnel --origincert=./cert.pem --config=./config.yml run coder
