name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    container:
      image: codercom/code-server:latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Run code-server
        run: |
          ls -al
          sudo curl -OL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          pwd
          touch cert.pem
          cat <<EOL >> cert.pem
          ${{secrets.CF_CERT}}
          EOL
          cloudflared tunnel --origincert cert.pem create coder
          cloudflared tunnel list
          sudo code-server
