name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
            
      - name: Prepare
        run: |
          mkdir -p ~/workspaces/aipic
          mkdir -p ~/.local/share/code-server
            
      - name: Clone Backups
        run: |
          git clone ${{secrets.WORK_REPO}} ~/workspaces/ai-arts
        
      - name: Run code-server
        timeout-minutes: 3
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          curl -OL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          touch ./cert.pem
          
          cat <<EOL >> ./cert.pem
          ${{secrets.CF_CERT}}
          EOL
          
          cat <<EOL >> ./config.yml
          ${{secrets.CF_YAML}}
          EOL

          cat <<EOL >> ./af573896-2e34-45cd-9037-1bbb9138bd27.json
          ${{secrets.CF_CFG}}
          EOL

          cat <<EOL >> ./code-server.yaml
          ${{secrets.CODE_SECRET}}
          EOL
          
          code-server --version
          code-server --config=./code-server.yaml ~/workspaces/ai-arts & cloudflared tunnel --origincert=./cert.pem --config=./config.yml run coder

      - name: Compress Artifact
        if: failure()
        run: |
          zip -e --password=${{secrets.ZIP_PASSWORD}} source.zip ~/workspaces/ai-arts
          zip -e --password=${{secrets.ZIP_PASSWORD}} cache.zip ~/.local/share/code-server
          
      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: source
          path: source.zip
          
      - name: Upload Cache
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cache
          path: cache.zip
          
