name: Coder
on: push

jobs:
  coder:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
            
      - name: Prepare Backup
        run: |
          mkdir -p ~/workspaces/aipic
          mkdir -p ~/.local/share/code-server
            
      - name: Clone Backups
        run: |
          git clone ${{secrets.WORK_REPO}} ~/workspaces/ai-arts

      - name: Download Backups cache
        uses: actions/download-artifact@v3
        with:
          name: cache
          
      - run: ls

      - name: Run code-server
        timeout-minutes: 1
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          curl -OL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          touch ./cert.pem
          
          cat <<EOL >> ./cert.pem
          ${{secrets.CF_CERT}}
          EOL
          
          cat <<EOL >> ./config.yml
          ${{secrets.CF_YAML}}
          EOL

          cat <<EOL >> ./af573896-2e34-45cd-9037-1bbb9138bd27.json
          ${{secrets.CF_CFG}}
          EOL

          cat <<EOL >> ./code-server.yaml
          ${{secrets.CODE_SECRET}}
          EOL
          
          code-server --version
          code-server --config=./code-server.yaml ~/workspaces/ai-arts & cloudflared tunnel --origincert=./cert.pem --config=./config.yml --loglevel=panic run coder

      - name: Compress Artifact
        if: failure()
        run: |
          cd ~/workspaces/ai-arts
          zip -er --password=${{secrets.ZIP_PASSWORD}} ${GITHUB_WORKSPACE}/source.zip * .[^.]*
          cd ~/.local/share/code-server
          zip -er --password=${{secrets.ZIP_PASSWORD}} ${GITHUB_WORKSPACE}/cache.zip * .[^.]*
          cd ${GITHUB_WORKSPACE}
          
      - name: Upload Artifact
        if: failure()
        uses: softprops/action-gh-release@v1
        with:
          files: |
            source.zip
            cache.zip
          
